Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/09/2023
Var
   // Seção de Declarações das variáveis
   i,n:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

escreva("Digite um Número para a tabuada : ")
leia(n)
escreval(" ")

   para i de 0 ate 10  faca
      escreval(        n ," *", i," = ",n * i )
   fimpara


Fimalgoritmo